"""Enable Outbound Network Activities

Revision ID: 6dfba265232e
Revises: 3ecb7147c137
Create Date: 2020-07-16 09:41:58.110396+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfba265232e'
down_revision = '3ecb7147c137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_advanced', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adv_outbound_network', sa.Boolean(), default=True, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_advanced', schema=None) as batch_op:
        batch_op.drop_column('adv_outbound_network')

    # ### end Alembic commands ###
